/*
 * Copyright (C) 2024 Fraunhofer Institut IOSB, Fraunhoferstr. 1, D 76131
 * Karlsruhe, Germany.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package de.fraunhofer.iosb.ilt.frostclient.utils;

import static de.fraunhofer.iosb.ilt.frostclient.utils.StringHelper.isNullOrEmpty;

import java.net.URI;
import java.net.URISyntaxException;
import org.apache.http.client.methods.HttpRequestBase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * In some cases the server generates URLs using a different base URL. For
 * instance when the server has a different external and internal address. This
 * option will replace the start part of each URL generated by the server that
 * matches the given string, with the service URL.
 */
public class RequestHookUrlReplacer implements RequestHook {

    private static final Logger LOGGER = LoggerFactory.getLogger(RequestHookUrlReplacer.class.getName());

    private final String urlReplace;
    private final String baseUrl;

    public RequestHookUrlReplacer(String urlReplace, String baseUrl) {
        this.urlReplace = urlReplace;
        this.baseUrl = baseUrl;
    }

    @Override
    public HttpRequestBase handle(HttpRequestBase request) {
        final String urlString = request.getURI().toString();
        if (!isNullOrEmpty(urlReplace) && urlString.startsWith(urlReplace)) {
            final String newUrlString = baseUrl + urlString.substring(urlReplace.length());
            LOGGER.debug("   Fixed: {}", newUrlString);
            try {
                request.setURI(new URI(newUrlString));
            } catch (URISyntaxException ex) {
                throw new IllegalArgumentException("Failed to replace start of URL", ex);
            }
        }
        return request;
    }

}
