name: Maven Build

on:
  push:
    branches:
      - main
      - develop
      - develop-*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y-%m-%dT%H:%M:%S")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Restore CVD Database from Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.m2/repository/org/owasp/dependency-check-data
        key: ${{ runner.os }}-maven-owasp-cvedb-${{ steps.get-date.outputs.date }}
        restore-keys: ${{ runner.os }}-maven-owasp-cvedb

    - name: Update CVD Database
      continue-on-error: true
      env:
        NIST_NVD_API_KEY: ${{ secrets.NIST_NVD_API_KEY }}
      run: |
        mvn -B -DnvdApiDelay=6000 --settings scripts/maven-ci-settings.xml org.owasp:dependency-check-maven:update-only

    - name: Save CVD Database to Cache
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.m2/repository/org/owasp/dependency-check-data
        key: ${{ runner.os }}-maven-owasp-cvedb-${{ steps.get-date.outputs.date }}


    - name: Build with Maven
      env:
        OSSINDEX_TOKEN: ${{ secrets.OSSINDEX_TOKEN }}
        OSSINDEX_USERNAME: ${{ secrets.OSSINDEX_USERNAME }}
      run: mvn -B install --file pom.xml -DautoUpdate=false --settings scripts/maven-ci-settings.xml

